# Generated by Django 3.0.7 on 2020-09-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200911_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Users',
        ),
    ]
