# Generated by Django 3.0.7 on 2020-09-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200911_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='points',
            field=models.IntegerField(),
        ),
    ]
